// <auto-generated />
namespace Parkano2018Bot.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class migrate2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migrate2));
        
        string IMigrationMetadata.Id
        {
            get { return "201806210954496_migrate2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
